name: Art Islands Tokyo 2020
title: Charlotte Parallel Art Island Tokyo 2020
description: > # this means to ignore newlines until "baseurl:"
  EDIT_ME description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: /CPArtisland # the subpath of your site, e.g. /blog  EDIT_ME
url: http://charlotteparallel.github.io/ # the base hostname & protocol for your site, e.g. http://example.com     EDIT_ME
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Charlotte Parallel # add your name EDIT_ME

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
